"""add foreign key to Review

Revision ID: 19c136f8118e
Revises: e64f90154d6d
Create Date: 2024-07-02 23:55:41.577609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c136f8118e'
down_revision = 'e64f90154d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews') as batch_op:
        batch_op.drop_constraint(op.f('fk_reviews_employee_id_employees'), type_='foreignkey')
    # ### end Alembic commands ###
